/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOpsRouteImport } from './routes/_authenticated/ops'
import { Route as ApiOpsV1ConnectorsRouteImport } from './routes/api/ops/v1/connectors'
import { Route as ApiPublicHooksConfigSyncRouteImport } from './routes/api/public/hooks/config-sync'
import { Route as ApiPublicHooksSyncWorkerRouteImport } from './routes/api/public/hooks/sync-worker'
import { Route as ApiPublicV1BillingRouteImport } from './routes/api/public/v1/billing'
import { Route as ApiPublicV1ConfigRouteImport } from './routes/api/public/v1/config'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicV1RecipesRouteImport } from './routes/api/public/v1/recipes'
import { Route as ApiPublicV1SalesRouteImport } from './routes/api/public/v1/sales'
import { Route as ApiPublicV1InventoryAdjustmentRouteImport } from './routes/api/public/v1/inventory/adjustment'
import { Route as ApiPublicV1InventoryAdjustmentReasonsRouteImport } from './routes/api/public/v1/inventory/adjustment-reasons'
import { Route as ApiPublicV1InventoryConvertRouteImport } from './routes/api/public/v1/inventory/convert'
import { Route as ApiPublicV1InventoryInitialUploadRouteImport } from './routes/api/public/v1/inventory/initial-upload'
import { Route as ApiPublicV1InventoryProductStatusRouteImport } from './routes/api/public/v1/inventory/product-status'
import { Route as ApiPublicV1InventoryProductsRouteImport } from './routes/api/public/v1/inventory/products'
import { Route as ApiPublicV1InventorySyncRouteImport } from './routes/api/public/v1/inventory/sync'
import { Route as ApiPublicV1InventoryTransferRouteImport } from './routes/api/public/v1/inventory/transfer'
import { Route as ApiPublicV1InventoryWarehouseRouteImport } from './routes/api/public/v1/inventory/warehouse'
import { Route as ApiPublicV1SalesCreditDebitNoteRouteImport } from './routes/api/public/v1/sales/credit-debit-note'
import { Route as ApiPublicV1SalesInvoiceByNumberRouteImport } from './routes/api/public/v1/sales/invoice-by-number'
import { Route as ApiPublicV1StockAddProductRouteImport } from './routes/api/public/v1/stock/add-product'
import { Route as ApiPublicV1StockHsCodesRouteImport } from './routes/api/public/v1/stock/hs-codes'
import { Route as ApiPublicV1StockSuppliersRouteImport } from './routes/api/public/v1/stock/suppliers'
import { Route as ApiPublicV1TenantActivateRouteImport } from './routes/api/public/v1/tenant/activate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpsRoute = AuthenticatedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiOpsV1ConnectorsRoute = ApiOpsV1ConnectorsRouteImport.update({
  id: '/api/ops/v1/connectors',
  path: '/api/ops/v1/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksConfigSyncRoute =
  ApiPublicHooksConfigSyncRouteImport.update({
    id: '/api/public/hooks/config-sync',
    path: '/api/public/hooks/config-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncWorkerRoute =
  ApiPublicHooksSyncWorkerRouteImport.update({
    id: '/api/public/hooks/sync-worker',
    path: '/api/public/hooks/sync-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1BillingRoute = ApiPublicV1BillingRouteImport.update({
  id: '/api/public/v1/billing',
  path: '/api/public/v1/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ConfigRoute = ApiPublicV1ConfigRouteImport.update({
  id: '/api/public/v1/config',
  path: '/api/public/v1/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RecipesRoute = ApiPublicV1RecipesRouteImport.update({
  id: '/api/public/v1/recipes',
  path: '/api/public/v1/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SalesRoute = ApiPublicV1SalesRouteImport.update({
  id: '/api/public/v1/sales',
  path: '/api/public/v1/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1InventoryAdjustmentRoute =
  ApiPublicV1InventoryAdjustmentRouteImport.update({
    id: '/api/public/v1/inventory/adjustment',
    path: '/api/public/v1/inventory/adjustment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InventoryAdjustmentReasonsRoute =
  ApiPublicV1InventoryAdjustmentReasonsRouteImport.update({
    id: '/api/public/v1/inventory/adjustment-reasons',
    path: '/api/public/v1/inventory/adjustment-reasons',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InventoryConvertRoute =
  ApiPublicV1InventoryConvertRouteImport.update({
    id: '/api/public/v1/inventory/convert',
    path: '/api/public/v1/inventory/convert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InventoryInitialUploadRoute =
  ApiPublicV1InventoryInitialUploadRouteImport.update({
    id: '/api/public/v1/inventory/initial-upload',
    path: '/api/public/v1/inventory/initial-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InventoryProductStatusRoute =
  ApiPublicV1InventoryProductStatusRouteImport.update({
    id: '/api/public/v1/inventory/product-status',
    path: '/api/public/v1/inventory/product-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InventoryProductsRoute =
  ApiPublicV1InventoryProductsRouteImport.update({
    id: '/api/public/v1/inventory/products',
    path: '/api/public/v1/inventory/products',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InventorySyncRoute =
  ApiPublicV1InventorySyncRouteImport.update({
    id: '/api/public/v1/inventory/sync',
    path: '/api/public/v1/inventory/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InventoryTransferRoute =
  ApiPublicV1InventoryTransferRouteImport.update({
    id: '/api/public/v1/inventory/transfer',
    path: '/api/public/v1/inventory/transfer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1InventoryWarehouseRoute =
  ApiPublicV1InventoryWarehouseRouteImport.update({
    id: '/api/public/v1/inventory/warehouse',
    path: '/api/public/v1/inventory/warehouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1SalesCreditDebitNoteRoute =
  ApiPublicV1SalesCreditDebitNoteRouteImport.update({
    id: '/credit-debit-note',
    path: '/credit-debit-note',
    getParentRoute: () => ApiPublicV1SalesRoute,
  } as any)
const ApiPublicV1SalesInvoiceByNumberRoute =
  ApiPublicV1SalesInvoiceByNumberRouteImport.update({
    id: '/invoice-by-number',
    path: '/invoice-by-number',
    getParentRoute: () => ApiPublicV1SalesRoute,
  } as any)
const ApiPublicV1StockAddProductRoute =
  ApiPublicV1StockAddProductRouteImport.update({
    id: '/api/public/v1/stock/add-product',
    path: '/api/public/v1/stock/add-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1StockHsCodesRoute = ApiPublicV1StockHsCodesRouteImport.update({
  id: '/api/public/v1/stock/hs-codes',
  path: '/api/public/v1/stock/hs-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StockSuppliersRoute =
  ApiPublicV1StockSuppliersRouteImport.update({
    id: '/api/public/v1/stock/suppliers',
    path: '/api/public/v1/stock/suppliers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TenantActivateRoute =
  ApiPublicV1TenantActivateRouteImport.update({
    id: '/api/public/v1/tenant/activate',
    path: '/api/public/v1/tenant/activate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/api/ops/v1/connectors': typeof ApiOpsV1ConnectorsRoute
  '/api/public/hooks/config-sync': typeof ApiPublicHooksConfigSyncRoute
  '/api/public/hooks/sync-worker': typeof ApiPublicHooksSyncWorkerRoute
  '/api/public/v1/billing': typeof ApiPublicV1BillingRoute
  '/api/public/v1/config': typeof ApiPublicV1ConfigRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/recipes': typeof ApiPublicV1RecipesRoute
  '/api/public/v1/sales': typeof ApiPublicV1SalesRouteWithChildren
  '/api/public/v1/inventory/adjustment': typeof ApiPublicV1InventoryAdjustmentRoute
  '/api/public/v1/inventory/adjustment-reasons': typeof ApiPublicV1InventoryAdjustmentReasonsRoute
  '/api/public/v1/inventory/convert': typeof ApiPublicV1InventoryConvertRoute
  '/api/public/v1/inventory/initial-upload': typeof ApiPublicV1InventoryInitialUploadRoute
  '/api/public/v1/inventory/product-status': typeof ApiPublicV1InventoryProductStatusRoute
  '/api/public/v1/inventory/products': typeof ApiPublicV1InventoryProductsRoute
  '/api/public/v1/inventory/sync': typeof ApiPublicV1InventorySyncRoute
  '/api/public/v1/inventory/transfer': typeof ApiPublicV1InventoryTransferRoute
  '/api/public/v1/inventory/warehouse': typeof ApiPublicV1InventoryWarehouseRoute
  '/api/public/v1/sales/credit-debit-note': typeof ApiPublicV1SalesCreditDebitNoteRoute
  '/api/public/v1/sales/invoice-by-number': typeof ApiPublicV1SalesInvoiceByNumberRoute
  '/api/public/v1/stock/add-product': typeof ApiPublicV1StockAddProductRoute
  '/api/public/v1/stock/hs-codes': typeof ApiPublicV1StockHsCodesRoute
  '/api/public/v1/stock/suppliers': typeof ApiPublicV1StockSuppliersRoute
  '/api/public/v1/tenant/activate': typeof ApiPublicV1TenantActivateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/api/ops/v1/connectors': typeof ApiOpsV1ConnectorsRoute
  '/api/public/hooks/config-sync': typeof ApiPublicHooksConfigSyncRoute
  '/api/public/hooks/sync-worker': typeof ApiPublicHooksSyncWorkerRoute
  '/api/public/v1/billing': typeof ApiPublicV1BillingRoute
  '/api/public/v1/config': typeof ApiPublicV1ConfigRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/recipes': typeof ApiPublicV1RecipesRoute
  '/api/public/v1/sales': typeof ApiPublicV1SalesRouteWithChildren
  '/api/public/v1/inventory/adjustment': typeof ApiPublicV1InventoryAdjustmentRoute
  '/api/public/v1/inventory/adjustment-reasons': typeof ApiPublicV1InventoryAdjustmentReasonsRoute
  '/api/public/v1/inventory/convert': typeof ApiPublicV1InventoryConvertRoute
  '/api/public/v1/inventory/initial-upload': typeof ApiPublicV1InventoryInitialUploadRoute
  '/api/public/v1/inventory/product-status': typeof ApiPublicV1InventoryProductStatusRoute
  '/api/public/v1/inventory/products': typeof ApiPublicV1InventoryProductsRoute
  '/api/public/v1/inventory/sync': typeof ApiPublicV1InventorySyncRoute
  '/api/public/v1/inventory/transfer': typeof ApiPublicV1InventoryTransferRoute
  '/api/public/v1/inventory/warehouse': typeof ApiPublicV1InventoryWarehouseRoute
  '/api/public/v1/sales/credit-debit-note': typeof ApiPublicV1SalesCreditDebitNoteRoute
  '/api/public/v1/sales/invoice-by-number': typeof ApiPublicV1SalesInvoiceByNumberRoute
  '/api/public/v1/stock/add-product': typeof ApiPublicV1StockAddProductRoute
  '/api/public/v1/stock/hs-codes': typeof ApiPublicV1StockHsCodesRoute
  '/api/public/v1/stock/suppliers': typeof ApiPublicV1StockSuppliersRoute
  '/api/public/v1/tenant/activate': typeof ApiPublicV1TenantActivateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ops': typeof AuthenticatedOpsRoute
  '/api/ops/v1/connectors': typeof ApiOpsV1ConnectorsRoute
  '/api/public/hooks/config-sync': typeof ApiPublicHooksConfigSyncRoute
  '/api/public/hooks/sync-worker': typeof ApiPublicHooksSyncWorkerRoute
  '/api/public/v1/billing': typeof ApiPublicV1BillingRoute
  '/api/public/v1/config': typeof ApiPublicV1ConfigRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/recipes': typeof ApiPublicV1RecipesRoute
  '/api/public/v1/sales': typeof ApiPublicV1SalesRouteWithChildren
  '/api/public/v1/inventory/adjustment': typeof ApiPublicV1InventoryAdjustmentRoute
  '/api/public/v1/inventory/adjustment-reasons': typeof ApiPublicV1InventoryAdjustmentReasonsRoute
  '/api/public/v1/inventory/convert': typeof ApiPublicV1InventoryConvertRoute
  '/api/public/v1/inventory/initial-upload': typeof ApiPublicV1InventoryInitialUploadRoute
  '/api/public/v1/inventory/product-status': typeof ApiPublicV1InventoryProductStatusRoute
  '/api/public/v1/inventory/products': typeof ApiPublicV1InventoryProductsRoute
  '/api/public/v1/inventory/sync': typeof ApiPublicV1InventorySyncRoute
  '/api/public/v1/inventory/transfer': typeof ApiPublicV1InventoryTransferRoute
  '/api/public/v1/inventory/warehouse': typeof ApiPublicV1InventoryWarehouseRoute
  '/api/public/v1/sales/credit-debit-note': typeof ApiPublicV1SalesCreditDebitNoteRoute
  '/api/public/v1/sales/invoice-by-number': typeof ApiPublicV1SalesInvoiceByNumberRoute
  '/api/public/v1/stock/add-product': typeof ApiPublicV1StockAddProductRoute
  '/api/public/v1/stock/hs-codes': typeof ApiPublicV1StockHsCodesRoute
  '/api/public/v1/stock/suppliers': typeof ApiPublicV1StockSuppliersRoute
  '/api/public/v1/tenant/activate': typeof ApiPublicV1TenantActivateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ops'
    | '/api/ops/v1/connectors'
    | '/api/public/hooks/config-sync'
    | '/api/public/hooks/sync-worker'
    | '/api/public/v1/billing'
    | '/api/public/v1/config'
    | '/api/public/v1/health'
    | '/api/public/v1/recipes'
    | '/api/public/v1/sales'
    | '/api/public/v1/inventory/adjustment'
    | '/api/public/v1/inventory/adjustment-reasons'
    | '/api/public/v1/inventory/convert'
    | '/api/public/v1/inventory/initial-upload'
    | '/api/public/v1/inventory/product-status'
    | '/api/public/v1/inventory/products'
    | '/api/public/v1/inventory/sync'
    | '/api/public/v1/inventory/transfer'
    | '/api/public/v1/inventory/warehouse'
    | '/api/public/v1/sales/credit-debit-note'
    | '/api/public/v1/sales/invoice-by-number'
    | '/api/public/v1/stock/add-product'
    | '/api/public/v1/stock/hs-codes'
    | '/api/public/v1/stock/suppliers'
    | '/api/public/v1/tenant/activate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ops'
    | '/api/ops/v1/connectors'
    | '/api/public/hooks/config-sync'
    | '/api/public/hooks/sync-worker'
    | '/api/public/v1/billing'
    | '/api/public/v1/config'
    | '/api/public/v1/health'
    | '/api/public/v1/recipes'
    | '/api/public/v1/sales'
    | '/api/public/v1/inventory/adjustment'
    | '/api/public/v1/inventory/adjustment-reasons'
    | '/api/public/v1/inventory/convert'
    | '/api/public/v1/inventory/initial-upload'
    | '/api/public/v1/inventory/product-status'
    | '/api/public/v1/inventory/products'
    | '/api/public/v1/inventory/sync'
    | '/api/public/v1/inventory/transfer'
    | '/api/public/v1/inventory/warehouse'
    | '/api/public/v1/sales/credit-debit-note'
    | '/api/public/v1/sales/invoice-by-number'
    | '/api/public/v1/stock/add-product'
    | '/api/public/v1/stock/hs-codes'
    | '/api/public/v1/stock/suppliers'
    | '/api/public/v1/tenant/activate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ops'
    | '/api/ops/v1/connectors'
    | '/api/public/hooks/config-sync'
    | '/api/public/hooks/sync-worker'
    | '/api/public/v1/billing'
    | '/api/public/v1/config'
    | '/api/public/v1/health'
    | '/api/public/v1/recipes'
    | '/api/public/v1/sales'
    | '/api/public/v1/inventory/adjustment'
    | '/api/public/v1/inventory/adjustment-reasons'
    | '/api/public/v1/inventory/convert'
    | '/api/public/v1/inventory/initial-upload'
    | '/api/public/v1/inventory/product-status'
    | '/api/public/v1/inventory/products'
    | '/api/public/v1/inventory/sync'
    | '/api/public/v1/inventory/transfer'
    | '/api/public/v1/inventory/warehouse'
    | '/api/public/v1/sales/credit-debit-note'
    | '/api/public/v1/sales/invoice-by-number'
    | '/api/public/v1/stock/add-product'
    | '/api/public/v1/stock/hs-codes'
    | '/api/public/v1/stock/suppliers'
    | '/api/public/v1/tenant/activate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiOpsV1ConnectorsRoute: typeof ApiOpsV1ConnectorsRoute
  ApiPublicHooksConfigSyncRoute: typeof ApiPublicHooksConfigSyncRoute
  ApiPublicHooksSyncWorkerRoute: typeof ApiPublicHooksSyncWorkerRoute
  ApiPublicV1BillingRoute: typeof ApiPublicV1BillingRoute
  ApiPublicV1ConfigRoute: typeof ApiPublicV1ConfigRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1RecipesRoute: typeof ApiPublicV1RecipesRoute
  ApiPublicV1SalesRoute: typeof ApiPublicV1SalesRouteWithChildren
  ApiPublicV1InventoryAdjustmentRoute: typeof ApiPublicV1InventoryAdjustmentRoute
  ApiPublicV1InventoryAdjustmentReasonsRoute: typeof ApiPublicV1InventoryAdjustmentReasonsRoute
  ApiPublicV1InventoryConvertRoute: typeof ApiPublicV1InventoryConvertRoute
  ApiPublicV1InventoryInitialUploadRoute: typeof ApiPublicV1InventoryInitialUploadRoute
  ApiPublicV1InventoryProductStatusRoute: typeof ApiPublicV1InventoryProductStatusRoute
  ApiPublicV1InventoryProductsRoute: typeof ApiPublicV1InventoryProductsRoute
  ApiPublicV1InventorySyncRoute: typeof ApiPublicV1InventorySyncRoute
  ApiPublicV1InventoryTransferRoute: typeof ApiPublicV1InventoryTransferRoute
  ApiPublicV1InventoryWarehouseRoute: typeof ApiPublicV1InventoryWarehouseRoute
  ApiPublicV1StockAddProductRoute: typeof ApiPublicV1StockAddProductRoute
  ApiPublicV1StockHsCodesRoute: typeof ApiPublicV1StockHsCodesRoute
  ApiPublicV1StockSuppliersRoute: typeof ApiPublicV1StockSuppliersRoute
  ApiPublicV1TenantActivateRoute: typeof ApiPublicV1TenantActivateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ops': {
      id: '/_authenticated/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AuthenticatedOpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ops/v1/connectors': {
      id: '/api/ops/v1/connectors'
      path: '/api/ops/v1/connectors'
      fullPath: '/api/ops/v1/connectors'
      preLoaderRoute: typeof ApiOpsV1ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/config-sync': {
      id: '/api/public/hooks/config-sync'
      path: '/api/public/hooks/config-sync'
      fullPath: '/api/public/hooks/config-sync'
      preLoaderRoute: typeof ApiPublicHooksConfigSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-worker': {
      id: '/api/public/hooks/sync-worker'
      path: '/api/public/hooks/sync-worker'
      fullPath: '/api/public/hooks/sync-worker'
      preLoaderRoute: typeof ApiPublicHooksSyncWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/billing': {
      id: '/api/public/v1/billing'
      path: '/api/public/v1/billing'
      fullPath: '/api/public/v1/billing'
      preLoaderRoute: typeof ApiPublicV1BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/config': {
      id: '/api/public/v1/config'
      path: '/api/public/v1/config'
      fullPath: '/api/public/v1/config'
      preLoaderRoute: typeof ApiPublicV1ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/recipes': {
      id: '/api/public/v1/recipes'
      path: '/api/public/v1/recipes'
      fullPath: '/api/public/v1/recipes'
      preLoaderRoute: typeof ApiPublicV1RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sales': {
      id: '/api/public/v1/sales'
      path: '/api/public/v1/sales'
      fullPath: '/api/public/v1/sales'
      preLoaderRoute: typeof ApiPublicV1SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/adjustment': {
      id: '/api/public/v1/inventory/adjustment'
      path: '/api/public/v1/inventory/adjustment'
      fullPath: '/api/public/v1/inventory/adjustment'
      preLoaderRoute: typeof ApiPublicV1InventoryAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/adjustment-reasons': {
      id: '/api/public/v1/inventory/adjustment-reasons'
      path: '/api/public/v1/inventory/adjustment-reasons'
      fullPath: '/api/public/v1/inventory/adjustment-reasons'
      preLoaderRoute: typeof ApiPublicV1InventoryAdjustmentReasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/convert': {
      id: '/api/public/v1/inventory/convert'
      path: '/api/public/v1/inventory/convert'
      fullPath: '/api/public/v1/inventory/convert'
      preLoaderRoute: typeof ApiPublicV1InventoryConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/initial-upload': {
      id: '/api/public/v1/inventory/initial-upload'
      path: '/api/public/v1/inventory/initial-upload'
      fullPath: '/api/public/v1/inventory/initial-upload'
      preLoaderRoute: typeof ApiPublicV1InventoryInitialUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/product-status': {
      id: '/api/public/v1/inventory/product-status'
      path: '/api/public/v1/inventory/product-status'
      fullPath: '/api/public/v1/inventory/product-status'
      preLoaderRoute: typeof ApiPublicV1InventoryProductStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/products': {
      id: '/api/public/v1/inventory/products'
      path: '/api/public/v1/inventory/products'
      fullPath: '/api/public/v1/inventory/products'
      preLoaderRoute: typeof ApiPublicV1InventoryProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/sync': {
      id: '/api/public/v1/inventory/sync'
      path: '/api/public/v1/inventory/sync'
      fullPath: '/api/public/v1/inventory/sync'
      preLoaderRoute: typeof ApiPublicV1InventorySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/transfer': {
      id: '/api/public/v1/inventory/transfer'
      path: '/api/public/v1/inventory/transfer'
      fullPath: '/api/public/v1/inventory/transfer'
      preLoaderRoute: typeof ApiPublicV1InventoryTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/inventory/warehouse': {
      id: '/api/public/v1/inventory/warehouse'
      path: '/api/public/v1/inventory/warehouse'
      fullPath: '/api/public/v1/inventory/warehouse'
      preLoaderRoute: typeof ApiPublicV1InventoryWarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sales/credit-debit-note': {
      id: '/api/public/v1/sales/credit-debit-note'
      path: '/credit-debit-note'
      fullPath: '/api/public/v1/sales/credit-debit-note'
      preLoaderRoute: typeof ApiPublicV1SalesCreditDebitNoteRouteImport
      parentRoute: typeof ApiPublicV1SalesRoute
    }
    '/api/public/v1/sales/invoice-by-number': {
      id: '/api/public/v1/sales/invoice-by-number'
      path: '/invoice-by-number'
      fullPath: '/api/public/v1/sales/invoice-by-number'
      preLoaderRoute: typeof ApiPublicV1SalesInvoiceByNumberRouteImport
      parentRoute: typeof ApiPublicV1SalesRoute
    }
    '/api/public/v1/stock/add-product': {
      id: '/api/public/v1/stock/add-product'
      path: '/api/public/v1/stock/add-product'
      fullPath: '/api/public/v1/stock/add-product'
      preLoaderRoute: typeof ApiPublicV1StockAddProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/stock/hs-codes': {
      id: '/api/public/v1/stock/hs-codes'
      path: '/api/public/v1/stock/hs-codes'
      fullPath: '/api/public/v1/stock/hs-codes'
      preLoaderRoute: typeof ApiPublicV1StockHsCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/stock/suppliers': {
      id: '/api/public/v1/stock/suppliers'
      path: '/api/public/v1/stock/suppliers'
      fullPath: '/api/public/v1/stock/suppliers'
      preLoaderRoute: typeof ApiPublicV1StockSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tenant/activate': {
      id: '/api/public/v1/tenant/activate'
      path: '/api/public/v1/tenant/activate'
      fullPath: '/api/public/v1/tenant/activate'
      preLoaderRoute: typeof ApiPublicV1TenantActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOpsRoute: typeof AuthenticatedOpsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOpsRoute: AuthenticatedOpsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1SalesRouteChildren {
  ApiPublicV1SalesCreditDebitNoteRoute: typeof ApiPublicV1SalesCreditDebitNoteRoute
  ApiPublicV1SalesInvoiceByNumberRoute: typeof ApiPublicV1SalesInvoiceByNumberRoute
}

const ApiPublicV1SalesRouteChildren: ApiPublicV1SalesRouteChildren = {
  ApiPublicV1SalesCreditDebitNoteRoute: ApiPublicV1SalesCreditDebitNoteRoute,
  ApiPublicV1SalesInvoiceByNumberRoute: ApiPublicV1SalesInvoiceByNumberRoute,
}

const ApiPublicV1SalesRouteWithChildren =
  ApiPublicV1SalesRoute._addFileChildren(ApiPublicV1SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiOpsV1ConnectorsRoute: ApiOpsV1ConnectorsRoute,
  ApiPublicHooksConfigSyncRoute: ApiPublicHooksConfigSyncRoute,
  ApiPublicHooksSyncWorkerRoute: ApiPublicHooksSyncWorkerRoute,
  ApiPublicV1BillingRoute: ApiPublicV1BillingRoute,
  ApiPublicV1ConfigRoute: ApiPublicV1ConfigRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1RecipesRoute: ApiPublicV1RecipesRoute,
  ApiPublicV1SalesRoute: ApiPublicV1SalesRouteWithChildren,
  ApiPublicV1InventoryAdjustmentRoute: ApiPublicV1InventoryAdjustmentRoute,
  ApiPublicV1InventoryAdjustmentReasonsRoute:
    ApiPublicV1InventoryAdjustmentReasonsRoute,
  ApiPublicV1InventoryConvertRoute: ApiPublicV1InventoryConvertRoute,
  ApiPublicV1InventoryInitialUploadRoute:
    ApiPublicV1InventoryInitialUploadRoute,
  ApiPublicV1InventoryProductStatusRoute:
    ApiPublicV1InventoryProductStatusRoute,
  ApiPublicV1InventoryProductsRoute: ApiPublicV1InventoryProductsRoute,
  ApiPublicV1InventorySyncRoute: ApiPublicV1InventorySyncRoute,
  ApiPublicV1InventoryTransferRoute: ApiPublicV1InventoryTransferRoute,
  ApiPublicV1InventoryWarehouseRoute: ApiPublicV1InventoryWarehouseRoute,
  ApiPublicV1StockAddProductRoute: ApiPublicV1StockAddProductRoute,
  ApiPublicV1StockHsCodesRoute: ApiPublicV1StockHsCodesRoute,
  ApiPublicV1StockSuppliersRoute: ApiPublicV1StockSuppliersRoute,
  ApiPublicV1TenantActivateRoute: ApiPublicV1TenantActivateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
