-- Seed the remaining built-in connectors (pre-integrated ERP/POS adapters)
INSERT INTO public.connectors (connector_type, label, auth_type, config_schema) VALUES
  ('aronium', 'Aronium POS', 'custom', '{"type":"object","properties":{"database_file":{"type":"string","title":"Aronium Database File (.db)"},"default_terminal_id":{"type":"string","title":"Default MRA Terminal ID"}},"required":[]}'),
  ('cliqpos', 'CliqPOS', 'custom', '{"type":"object","properties":{"merchant_id":{"type":"string","title":"Merchant ID"},"terminal_id":{"type":"string","title":"Terminal ID"},"api_key":{"type":"string","title":"API Key"},"default_terminal_id":{"type":"string","title":"Default MRA Terminal ID"}},"required":[]}'),
  ('erpnext', 'ERPNext', 'api_key', '{"type":"object","properties":{"url":{"type":"string","title":"ERPNext URL"},"api_key":{"type":"string","title":"API Key"},"api_secret":{"type":"string","title":"API Secret"},"default_terminal_id":{"type":"string","title":"Default MRA Terminal ID"}},"required":[]}'),
  ('kiboerp', 'Kibo ERP', 'api_key', '{"type":"object","properties":{"tenant":{"type":"string","title":"Tenant"},"site":{"type":"string","title":"Site"},"client_id":{"type":"string","title":"Client ID"},"shared_secret":{"type":"string","title":"Shared Secret"},"default_terminal_id":{"type":"string","title":"Default MRA Terminal ID"}},"required":[]}'),
  ('sage', 'Sage (Pastel / Evolution)', 'custom', '{"type":"object","properties":{"csv_url":{"type":"string","title":"Inventory CSV URL"},"default_terminal_id":{"type":"string","title":"Default MRA Terminal ID"}},"required":[]}'),
  ('sap-b1', 'SAP Business One', 'basic', '{"type":"object","properties":{"url":{"type":"string","title":"Service Layer URL"},"username":{"type":"string","title":"Username"},"password":{"type":"string","title":"Password"},"company_db":{"type":"string","title":"Company Database"},"default_terminal_id":{"type":"string","title":"Default MRA Terminal ID"}},"required":[]}'),
  ('tally', 'Tally ERP 9', 'custom', '{"type":"object","properties":{"url":{"type":"string","title":"Tally URL"},"port":{"type":"number","title":"Tally Port"},"default_terminal_id":{"type":"string","title":"Default MRA Terminal ID"}},"required":[]}')
ON CONFLICT (connector_type) DO NOTHING;
